blank_issues_enabled: false

contact_links:
  - name: Feature requests
    url: https://github.com/shiena/godot-neovim/discussions/categories/ideas
    about: Please suggest new features in GitHub Discussions.

  - name: Questions
    url: https://github.com/shiena/godot-neovim/discussions/categories/q-a
    about: Please ask questions in GitHub Discussions, not here.
